/**
 * Creates an anomaly object.
 *
 * Anomalies are generated by detection modules and contain
 * contextual information required for alert generation and analysis.
 *
 * @param {Object} params
 * @param {string} params.anomalyType - Type of anomaly (e.g., THRESHOLD_HIGH, TREND)
 * @param {string} params.measurementType - Measurement type associated with the anomaly
 * @param {number} params.observedValue - Observed measurement value
 * @param {Object|null} params.expectedRange - Expected physiological range (if applicable)
 * @param {string} params.detectionTimestamp - ISO timestamp of detection
 * @param {string} params.message - Human-readable description
 * @param {Object} params.context - Additional anomaly context
 *
 * @returns {Object} Anomaly object
 */
function createAnomaly({
    anomalyType,
    measurementType,
    observedValue,
    expectedRange,
    detectionTimestamp,
    message,
    context
  }) {
    return {
      anomalyType,
      measurementType,
      observedValue,
      expectedRange,
      detectionTimestamp,
      message,
      context
    };
  }
  
  module.exports = { createAnomaly };
  